resources:
# resource for triggering pipeline
- name: c3psnow
  type: git
  icon: github
  source:
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-queue
    username: ((git.username))
    password: ((git.password))
    ignore_paths:
    - README.md
    - pipeline.yaml
    - kubernetes
    - .gitignore
# resource of where to push image
- name: c3psnow-image
  type: registry-image
  icon: gitlab
  source:
    repository: ((gitlab.repository))/c3psnow/c3psnow
    username: ((gitlab.username))
    password: ((gitlab.password))
    variant: dev
# resource to send to slack
- name: notifier
  type: slack-notifier
  source:
    url: ((slack.webhook))

# add slack resource
resource_types:
- name: slack-notifier
  type: docker-image
  source:
    repository: mockersf/concourse-slack-notifier

jobs:
- name: build-and-push
  plan:
  - put: notifier
    params:
      alert_type: started
  - get: c3psnow
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: c3psnow
      outputs:
      - name: image
      params:
        CONTEXT: c3psnow
      run:
        path: build
  - put: c3psnow-image
    params:
      image: image/image.tar
      version: '0.1.1'
  - put: notifier
    params:
      alert_type: success
  on_failure:
    put: notifier
    params:
      alert_type: failed
