resources:
# resource for triggering pipeline; read-only
- name: repo-read
  type: git
  icon: github
  source:
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-auto-tag
    username: ((git.username))
    password: ((git.password))
    ignore_paths:
    - README.md
    - pipeline.yaml
    - kubernetes
    - .gitignore
    - version
# resource for writing to repository; write-only to avoid retriggering pipeline
- name: repo-write
  type: git
  icon: github
  source:
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-auto-tag
    username: ((git.username))
    password: ((git.password))
# resource of where to push image
- name: registry
  type: registry-image
  icon: gitlab
  source:
    repository: ((gitlab.repository))/c3psnow/c3psnow
    username: ((gitlab.username))
    password: ((gitlab.password))
    variant: dev
# resource for versioning
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-auto-tag
    username: ((git.username))
    password: ((git.password))
    file: version
# resource to send to slack
- name: notifier
  type: slack-notifier
  source:
    url: ((slack.webhook))

# add slack resource
resource_types:
- name: slack-notifier
  type: docker-image
  source:
    repository: mockersf/concourse-slack-notifier

jobs:
- name: set-pipeline
  plan:
- name: build-and-push-image
  plan:
  - put: notifier
    params:
      alert_type: started
  - get: repo-read
    trigger: true
  - set_pipeline: c3psnow-dev
    file: repo-read/pipeline.yml
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: repo-read
      outputs:
      - name: image
      - name: repo-read
      params:
        CONTEXT: repo-read
      run:
        path: build
  - get: version
    params:
      bump: patch
  - load_var: version_num
    file: version/version
  - put: registry
    params:
      image: image/image.tar
      version: ((.:version_num))
      bump_aliases: true
  - get: repo-write
  - task: bump-with-yq
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: docker.io/mikefarah/yq
      inputs: 
      - name: repo-write
      outputs:
      - name: repo-write
      run:
        path: sh
        args:
        - -exc
        - |
          cd repo-write
          yq -i '.spec.template.spec.containers[0].image = "((gitlab.repository))/c3psnow/c3psnow:((.:version_num))-dev"' kubernetes/c3psnow-deployment.yml
        user: root
  - task: git-push-bump
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: docker.io/alpine/git
      inputs: 
      - name: repo-write
      outputs:
      - name: repo-write
      run:
        path: sh
        args:
        - -exc
        - |
          cd repo-write
          git config --global user.email '<>'
          git config --global user.name "Concourse Bot"
          git add kubernetes/c3psnow-deployment.yml
          git commit -m 'bump version ((.:version_num))'
  - put: repo-write
    params:
      repository: repo-write
  - put: version
    params:
      file: version/version
  - put: notifier
    params:
      alert_type: success
  on_failure:
    put: notifier
    params:
      alert_type: failed
