resources:
# resource for triggering pipeline
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-auto-tag
    username: ((git.username))
    password: ((git.password))
    ignore_paths:
    - README.md
    - pipeline.yaml
    - kubernetes
    - .gitignore
    - version
# resource of where to push image
- name: registry
  type: registry-image
  icon: gitlab
  source:
    repository: ((gitlab.repository))/c3psnow/c3psnow
    username: ((gitlab.username))
    password: ((gitlab.password))
    variant: dev
# resource for versioning
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-auto-tag
    username: ((git.username))
    password: ((git.password))
    file: version
# resource to send to slack
- name: notifier
  type: slack-notifier
  source:
    driver: git
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-auto-tag
    username: ((git.username))
    password: ((git.password))
    file: version

jobs:
- name: ci-cd
  plan:
  - put: notifier
    params:
      alert_type: started
  - get: repo
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: repo
      outputs:
      - name: image
      - name: repo
      params:
        CONTEXT: repo
      run:
        path: build
  - get: version
    params:
      bump: patch
  - load_var: version_num
    file: version/version
  - put: registry
    params:
      image: image/image.tar
      version: ((.:version_num))
      bump_aliases: true
  - task: bump-with-yq
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: docker.io/mikefarah/yq
      inputs: 
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        args:
        - -exc
        - |
          cd repo
          yq -i '.spec.template.spec.containers[0].image = "((gitlab.repository))/c3psnow/c3psnow:((.:version_num))-dev"' kubernetes/c3psnow-deployment.yml
        user: root
  - task: git-push-bump
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: docker.io/alpine/git
      inputs: 
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        args:
        - -exc
        - |
          cd repo
          git config --global user.email '<>'
          git config --global user.name "Concourse Bot"
          git add kubernetes/c3psnow-deployment.yml
          git commit -m 'bump version ((.:version_num))'
  - put: repo
    params:
      repository: repo
  - put: version
    params:
      file: version/version
  - put: notifier
    params:
      alert_type: success
  on_failure:
    put: notifier
    params:
      repository: c3psnow
      only_tag: true
      tag: c3psnow/version
      tag_prefix: v
