resources:
# resource for triggering pipeline
- name: c3psnow
  type: git
  icon: github
  source:
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-auto-tag
    username: ((git.username))
    password: ((git.password))
    ignore_paths:
    - README.md
    - pipeline.yaml
    - kubernetes
    - .gitignore
    - version
# resource of where to push image
- name: c3psnow-image
  type: registry-image
  icon: gitlab
  source:
    repository: ((gitlab.repository))/c3psnow/c3psnow
    username: ((gitlab.username))
    password: ((gitlab.password))
    variant: dev
# resoruce to bump version
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/CC-Digital-Innovation/C3PSNOW.git
    branch: feat-auto-tag
    username: ((git.username))
    password: ((git.password))
    file: version

jobs:
- name: build-and-push
  plan:
  - get: c3psnow
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: c3psnow
      outputs:
      - name: image
      - name: c3psnow
      params:
        CONTEXT: c3psnow
      run:
        path: build
  - put: version
    params:
      bump: patch
  - load_var: version_num
    file: version/version
  - put: c3psnow-image
    params:
      image: image/image.tar
      version: ((.:version_num))
      bump_aliases: true
  - put: c3psnow
    params:
      repository: c3psnow
      only_tag: true
      tag: c3psnow/version
      tag_prefix: v
