apiVersion: apps/v1
kind: Deployment
metadata:
  name: c3psnow
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: c3psnow
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'c3psnow'
        vault.hashicorp.com/agent-inject-secret-api: 'concourse/main/c3psnow/api'
        vault.hashicorp.com/agent-inject-template-api: |
          {{- with secret "concourse/main/c3psnow/api" -}}
            export API_KEY="{{ .Data.data.token }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-snow: 'concourse/main/c3psnow/snow'
        vault.hashicorp.com/agent-inject-template-snow: |
          {{- with secret "concourse/main/c3psnow/snow" -}}
            export SNOW_INST="{{ .Data.data.instance }}"
            export SNOW_USER="{{ .Data.data.username }}"
            export SNOW_PASS="{{ .Data.data.password }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-noco: 'concourse/main/c3psnow/noco'
        vault.hashicorp.com/agent-inject-template-noco: |
          {{- with secret "concourse/main/c3psnow/noco" -}}
            export NOCO_KEY="{{ .Data.data.api_key }}"
          {{- end }}
      labels:
        app: c3psnow
    spec:
      containers:
      - image: registry.quokka.ninja/ccfs/c3psnow/c3psnow:0.1.1
        name: c3psnow
        args:
          [ '/bin/bash', '-c', 'source /vault/secrets/api && source /vault/secrets/snow && source /vault/secrets/noco && python main.py' ]
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: gitlab-cr
      serviceAccountName: c3psnow
