apiVersion: apps/v1
kind: Deployment
metadata:
  name: c3psnow
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: c3psnow
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'c3psnow'
        vault.hashicorp.com/agent-inject-secret-secrets: 'secret/c3psnow'
        vault.hashicorp.com/agent-inject-template-secrets: |
          {{- with secret "secret/c3psnow" -}}
            export API_KEY="{{ .Data.data.api_key }}"
            export SNOW_INST="{{ .Data.data.snow_instance }}"
            export SNOW_USER="{{ .Data.data.snow_user }}"
            export SNOW_PASS="{{ .Data.data.snow_password }}"
            export NOCO_KEY="{{ .Data.data.noco_key }}"
            export NOCO_URL="{{ .Data.data.noco_url }}"
          {{- end }}
      labels:
        app: c3psnow
    spec:
      containers:
      - image: registry.quokka.ninja/ccfs/c3psnow:1.0.0
        name: c3psnow
        args:
          [ '/bin/bash', '-c', 'source /vault/secrets/secrets && uvicorn c3api:app --host 0.0.0.0 --port 8000 --root-path /c3psnow' ]
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 100Mi
      imagePullSecrets:
        - name: gitlab-cr
      serviceAccountName: c3psnow
