apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: c3psnow
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: c3psnow
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70